### ISSUE TITLE
Chapter 4 Car Auction running auction.sol on Remix IDE

### ISSUE THREAD

**Issue by walter-grace** [PacktPublishing/Blockchain-By-Example#1]
I am currently reading the ebook and I am following along on the ETH section; I copied and paste your code from github; it seems the Auction smart contract works, but I am having issues with MyAuction _creation of MyAuction errored: Error encoding arguments: Error: invalid address (arg="", type="string", value="")_ Here is the error I am getting, any help would be great

**Comment by walter-grace** [comment]
Now I am getting this error after having it work a few times on both contracts _creation of Auction errored: VM Exception while processing transaction: revert_

**Comment by bellaj** [comment]
When you deploy the contract you need to define the arguments of the constructor in the input in front of deploy button.Here's an example 
`1564790400,0x953a435b43b605079b42b5e26922d425fdc31c89, "audi", 1999
`

**Comment by walter-grace** [comment]
Yes indeed that worked!
