### ISSUE TITLE
Chapter 5 when clicking 'Join Game' no ether is showing up, failed transaction;

### ISSUE THREAD

**Issue by walter-grace** [PacktPublishing/Blockchain-By-Example#3]
Getting failed transactions for joining game, no ether is showing up to accept the contract. Hope the pics help
My first contract went through but it wasn't showing a larger number of eth.
<img width="353" alt="Screen Shot 2019-08-09 at 10 44 04 AM" src="https://user-images.githubusercontent.com/31444892/62798351-eadf3900-ba92-11e9-9cf3-badde0e0035b.png">
<img width="349" alt="Screen Shot 2019-08-09 at 10 45 44 AM" src="https://user-images.githubusercontent.com/31444892/62798360-efa3ed00-ba92-11e9-81aa-8586f4bc21ae.png">

**Comment by bellaj** [comment]
If you're using ganache you should import one of the accounts provided. Once correctly done you should have enough ethers to join the game.

As you know `Join` method has 2 conditions 
```
require(Tplayer.exist(msg.sender), "player doesn't exist");
require(msg.value >= 1 ether && Tpension[msg.sender] == 0, "send higher pension");
```
which means that
- Player should be registered in the `Cplayer` contract:
- Player should send enough money ( one ether or more): msg.value >= 1 ether
that said check if you're already registered in Cplayer contract by calling `findPlayer`  method (it should return your details)

Hint : Try to use remix to get back the  message thrown by require
